name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *" # Runs daily at midnight UTC
  workflow_dispatch: # Allow manual runs

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: shohag1102 # Replace with your username
          svg_path: ./output/snake.svg

      - name: Commit and push
        run: |
          git config --global user.name "Your Name"
          git config --global user.email "your-email@example.com"
          git add ./output/snake.svg
          git commit -m "Update snake animation"
          git push